#!/bin/sh

# install with:
#   ln -s ../../pre-commit .git/hooks/pre-commit

# Ensures example.env is always accurate
# updates example.env by stripping values from .env
sed -r "/^[[:space:]]*#/!s|([^=]+=).*|\1|g" ".env" > "example.env"
git add "example.env"
